/** Centralized default UI copy. */
export const copy = {
  site: {
    name: "Meow Wall",
    tagline: "Pixel Cat Head Gallery & Studio",
    footer: "Built with agent-hub mascot · Customs stay in your browser",
    repo: "GitHub",
    repoUrl: "https://github.com/zjl1985/meow-wall",
  },
  nav: {
    wall: "Index",
    studio: "Studio",
    says: "Says",
    favorites: "Saved",
  },
  hero: {
    eyebrow: "Selected work / 01",
    title: "On Display",
    hint: "Press Space / R to pick a cat · 10 picks unlock a special parade",
    roll: "Pick a Cat",
    rollCount: (count: number) => `${count} rolls`,
    makeOne: "Open Studio",
  },
  specials: {
    title: "Specials",
    subtitle: "Nicole · Goodman · Simon · Zero",
  },
  wall: {
    title: "Archive",
    subtitle: (total: number, custom: number) =>
      custom > 0
        ? `${total} skins · ${custom} custom`
        : `${total} skins from agent-hub`,
    reshuffle: "Shuffle",
  },
  card: {
    favorite: "Save",
    unfavorite: "Unsave",
    preview: "Open",
    customBadge: "Custom",
    specialBadge: "Special",
  },
  studio: {
    title: "Studio",
    subtitle: "Tune colors, accessories, and moods. Save it to the Archive.",
    name: "Name",
    namePlaceholder: "Name this cat",
    colors: "Palette",
    accessories: "Props",
    expression: "Mood",
    randomize: "Random",
    reset: "Reset",
    save: "Save to Archive",
    saved: "Saved",
    exportSvg: "Export SVG",
    noneAccessory: "None",
  },
  palette: {
    head: "Head",
    headDark: "Dark",
    headLight: "Light",
    earInner: "Ear",
    ink: "Ink",
    blush: "Blush",
    nose: "Nose",
    white: "White",
  },
  accessory: {
    sunglasses: "Sunglasses",
    bowtie: "Bowtie",
    headphones: "Headphones",
    crown: "Crown",
    scarf: "Scarf",
    glasses: "Glasses",
    flower: "Flower",
    cap: "Cap",
    headband: "Headband",
    leaf: "Leaf",
    "gold-chain": "Chain",
  },
  says: {
    title: "Says",
    subtitle: "Give a cat a line and it will appear in a speech bubble.",
    placeholder: "e.g. I need coffee",
    submit: "Say it",
    presets: ["No more meetings", "One more coffee", "Meow", "No touching", "Doing my best"],
    empty: "Type something first",
    tooLong: (max: number) => `Max ${max} chars`,
    pickCat: "Another cat",
  },
  favorites: {
    title: "Saved",
    subtitle: (count: number) => `${count} cats`,
    clear: "Clear all",
    empty: "Nothing saved yet",
    emptyHint: "Save from Index, or make one in Studio",
    goWall: "Index",
    goStudio: "Studio",
  },
  toast: {
    favorited: "Saved",
    unfavorited: "Removed",
    cleared: "Cleared",
    customSaved: "Saved to Archive",
    exported: "SVG downloaded",
  },
  easterEgg: {
    sound: "Meow",
    parade: "Specials on parade",
    awayTitle: "come back...",
  },
  state: {
    idle: "Idle",
    thinking: "Think",
    success: "Happy",
    error: "Oops",
    sleeping: "Sleep",
    angry: "Mad",
  },
} as const;

export const MAX_SAYS_LENGTH = 24;
export const REPO_URL = copy.site.repoUrl;
