/** 全站文案集中在这里，组件里不写死中文 */
export const copy = {
  site: {
    name: "喵喵墙",
    tagline: "捏一只专属像素猫，收藏 agent-hub 同款猫猫头",
    footer: "像素猫来自 Fabel CONSULTING AI / agent-hub mascot · 自定义猫只存在你浏览器里",
  },
  nav: {
    wall: "猫墙",
    studio: "捏猫",
    says: "猫猫说话",
    favorites: "收藏",
  },
  hero: {
    eyebrow: "PIXEL CAT PLAYGROUND",
    title: "今天的猫是这只",
    hint: "空格 / R 换猫换表情 · 连换 10 次解锁专属猫游行",
    roll: "换一只",
    rollCount: (count: number) => `已经换了 ${count} 只`,
    makeOne: "去捏一只新的",
  },
  specials: {
    title: "彩蛋专属猫",
    subtitle: "Nicole · Goodman · Simon · Zero，agent-hub 里的那几只",
  },
  wall: {
    title: "猫墙",
    subtitle: (total: number, custom: number) =>
      custom > 0
        ? `${total} 只在场，其中 ${custom} 只是你捏的`
        : `一共 ${total} 款像素皮肤，全是 agent-hub 同款`,
    reshuffle: "打乱一下",
  },
  card: {
    favorite: "收藏",
    unfavorite: "取消收藏",
    preview: "看大猫",
    customBadge: "自制",
    specialBadge: "彩蛋",
  },
  studio: {
    title: "捏一只猫猫头",
    subtitle: "调颜色、戴配饰、换表情，保存后会出现在猫墙上",
    name: "名字",
    namePlaceholder: "给它起个名字",
    colors: "配色",
    accessories: "配饰",
    expression: "表情",
    randomize: "随机来一只",
    reset: "重置",
    save: "存进猫墙",
    saved: "已存进猫墙",
    exportSvg: "导出 SVG",
    noneAccessory: "素颜",
  },
  palette: {
    head: "主色",
    headDark: "深色",
    headLight: "浅色",
    earInner: "耳内",
    ink: "墨线",
    blush: "腮红",
    nose: "鼻子",
    white: "高光",
  },
  accessory: {
    sunglasses: "墨镜",
    bowtie: "领结",
    headphones: "耳机",
    crown: "王冠",
    scarf: "围巾",
    glasses: "眼镜",
    flower: "小花",
    cap: "帽子",
    headband: "头带",
    leaf: "叶子",
    "gold-chain": "金链",
  },
  says: {
    title: "让猫替你说话",
    subtitle: "选一只像素猫，输入一句话，它头顶冒泡",
    placeholder: "比如：我不想上班",
    submit: "让它说",
    presets: ["我不想上班", "再来一杯", "喵", "别摸我", "今天也很努力"],
    empty: "先输入一句话吧",
    tooLong: (max: number) => `最多 ${max} 个字`,
    pickCat: "换一只说话的猫",
  },
  favorites: {
    title: "我的收藏",
    subtitle: (count: number) => `一共 ${count} 只猫住在这里`,
    clear: "清空全部",
    empty: "还没有收藏任何猫",
    emptyHint: "去猫墙点爱心，或先去捏一只",
    goWall: "去猫墙",
    goStudio: "去捏猫",
  },
  toast: {
    favorited: "收下了，这只猫是你的了",
    unfavorited: "已经放它走了",
    cleared: "猫猫们都散场了",
    customSaved: "新猫入住猫墙了",
    exported: "SVG 已下载",
  },
  easterEgg: {
    sound: "喵一声",
    parade: "彩蛋猫大游行！Nicole / Goodman / Simon / Zero 出动",
    awayTitle: "🐱 快回来…",
  },
  state: {
    idle: "发呆",
    thinking: "思考中",
    success: "开心",
    error: "懵了",
    sleeping: "睡觉",
    angry: "生气",
  },
} as const;

export const MAX_SAYS_LENGTH = 24;
